# coding: utf-8

"""
    Currencydatafeed.com API V2

    > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found.   # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.forex_api import ForexApi  # noqa: E501
from swagger_client.rest import ApiException


class TestForexApi(unittest.TestCase):
    """ForexApi unit test stubs"""

    def setUp(self):
        self.api = ForexApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_convert_amount(self):
        """Test case for convert_amount

        Convert an amount between two currencies  # noqa: E501
        """
        pass

    def test_get_historical_ohlc(self):
        """Test case for get_historical_ohlc

        Get historical OHLC data for a currency pair on a given date  # noqa: E501
        """
        pass

    def test_get_intraday_ohlc(self):
        """Test case for get_intraday_ohlc

        Get intraday (minute/hour) OHLC data for a symbol with flexible time selection  # noqa: E501
        """
        pass

    def test_get_levels(self):
        """Test case for get_levels

        Technical Analysis - Get Support, Resistence, Bollinger Bands for a symbol  # noqa: E501
        """
        pass

    def test_get_live_rates(self):
        """Test case for get_live_rates

        Get live forex prices  # noqa: E501
        """
        pass

    def test_get_ohlcby_timeframe(self):
        """Test case for get_ohlcby_timeframe

        Get historical OHLC data for a currency pair within a date range  # noqa: E501
        """
        pass

    def test_get_performance(self):
        """Test case for get_performance

        Get percentage changes for a symbol for different periods  # noqa: E501
        """
        pass

    def test_get_rates_by_source(self):
        """Test case for get_rates_by_source

        Get rates with other currencies using a custom base currency  # noqa: E501
        """
        pass

    def test_get_technical_analysis(self):
        """Test case for get_technical_analysis

        Get technical analysis indicators for a symbol (Ema & Sma Levels, CCI, Williams%R, ADX and Stochastic Indicators)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
