/*
 * Currencydatafeed.com API V2
 * > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found. 
 *
 * OpenAPI spec version: 2.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InlineResponse200Symbols model module.
 * @module model/InlineResponse200Symbols
 * @version 2.0.1
 */
export default class InlineResponse200Symbols {
  /**
   * Constructs a new <code>InlineResponse200Symbols</code>.
   * @alias module:model/InlineResponse200Symbols
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse200Symbols</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse200Symbols} obj Optional instance to populate.
   * @return {module:model/InlineResponse200Symbols} The populated <code>InlineResponse200Symbols</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse200Symbols();
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'String');
    }
    return obj;
  }
}

/**
 * Symbol code (e.g. \"EURUSD\" or \"BTCUSDT\")
 * @member {String} symbol
 */
InlineResponse200Symbols.prototype.symbol = undefined;

/**
 * Name/description of the symbol or pair
 * @member {String} name
 */
InlineResponse200Symbols.prototype.name = undefined;

/**
 * Last updated datetime or timestamp
 * @member {String} updated
 */
InlineResponse200Symbols.prototype.updated = undefined;

