/*
 * Currencydatafeed.com API V2
 * > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found. 
 *
 * OpenAPI spec version: 2.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InlineResponse2009TechnicalData model module.
 * @module model/InlineResponse2009TechnicalData
 * @version 2.0.1
 */
export default class InlineResponse2009TechnicalData {
  /**
   * Constructs a new <code>InlineResponse2009TechnicalData</code>.
   * @alias module:model/InlineResponse2009TechnicalData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2009TechnicalData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2009TechnicalData} obj Optional instance to populate.
   * @return {module:model/InlineResponse2009TechnicalData} The populated <code>InlineResponse2009TechnicalData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2009TechnicalData();
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('sma_10'))
        obj.sma10 = ApiClient.convertToType(data['sma_10'], 'Number');
      if (data.hasOwnProperty('sma_20'))
        obj.sma20 = ApiClient.convertToType(data['sma_20'], 'Number');
      if (data.hasOwnProperty('sma_50'))
        obj.sma50 = ApiClient.convertToType(data['sma_50'], 'Number');
      if (data.hasOwnProperty('sma_100'))
        obj.sma100 = ApiClient.convertToType(data['sma_100'], 'Number');
      if (data.hasOwnProperty('sma_200'))
        obj.sma200 = ApiClient.convertToType(data['sma_200'], 'Number');
      if (data.hasOwnProperty('ema_12'))
        obj.ema12 = ApiClient.convertToType(data['ema_12'], 'Number');
      if (data.hasOwnProperty('ema_26'))
        obj.ema26 = ApiClient.convertToType(data['ema_26'], 'Number');
      if (data.hasOwnProperty('ema_50'))
        obj.ema50 = ApiClient.convertToType(data['ema_50'], 'Number');
      if (data.hasOwnProperty('stochastic_k'))
        obj.stochasticK = ApiClient.convertToType(data['stochastic_k'], 'Number');
      if (data.hasOwnProperty('stochastic_d'))
        obj.stochasticD = ApiClient.convertToType(data['stochastic_d'], 'Number');
      if (data.hasOwnProperty('adx'))
        obj.adx = ApiClient.convertToType(data['adx'], 'Number');
      if (data.hasOwnProperty('cci'))
        obj.cci = ApiClient.convertToType(data['cci'], 'Number');
      if (data.hasOwnProperty('williams_r'))
        obj.williamsR = ApiClient.convertToType(data['williams_r'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Date} _date
 */
InlineResponse2009TechnicalData.prototype._date = undefined;

/**
 * @member {Number} sma10
 */
InlineResponse2009TechnicalData.prototype.sma10 = undefined;

/**
 * @member {Number} sma20
 */
InlineResponse2009TechnicalData.prototype.sma20 = undefined;

/**
 * @member {Number} sma50
 */
InlineResponse2009TechnicalData.prototype.sma50 = undefined;

/**
 * @member {Number} sma100
 */
InlineResponse2009TechnicalData.prototype.sma100 = undefined;

/**
 * @member {Number} sma200
 */
InlineResponse2009TechnicalData.prototype.sma200 = undefined;

/**
 * @member {Number} ema12
 */
InlineResponse2009TechnicalData.prototype.ema12 = undefined;

/**
 * @member {Number} ema26
 */
InlineResponse2009TechnicalData.prototype.ema26 = undefined;

/**
 * @member {Number} ema50
 */
InlineResponse2009TechnicalData.prototype.ema50 = undefined;

/**
 * @member {Number} stochasticK
 */
InlineResponse2009TechnicalData.prototype.stochasticK = undefined;

/**
 * @member {Number} stochasticD
 */
InlineResponse2009TechnicalData.prototype.stochasticD = undefined;

/**
 * @member {Number} adx
 */
InlineResponse2009TechnicalData.prototype.adx = undefined;

/**
 * @member {Number} cci
 */
InlineResponse2009TechnicalData.prototype.cci = undefined;

/**
 * @member {Number} williamsR
 */
InlineResponse2009TechnicalData.prototype.williamsR = undefined;

