/*
 * Currencydatafeed.com API V2
 * > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found. 
 *
 * OpenAPI spec version: 2.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InlineResponse2009RsiData model module.
 * @module model/InlineResponse2009RsiData
 * @version 2.0.1
 */
export default class InlineResponse2009RsiData {
  /**
   * Constructs a new <code>InlineResponse2009RsiData</code>.
   * @alias module:model/InlineResponse2009RsiData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2009RsiData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2009RsiData} obj Optional instance to populate.
   * @return {module:model/InlineResponse2009RsiData} The populated <code>InlineResponse2009RsiData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2009RsiData();
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('rsi'))
        obj.rsi = ApiClient.convertToType(data['rsi'], 'Number');
      if (data.hasOwnProperty('rsi_signal'))
        obj.rsiSignal = ApiClient.convertToType(data['rsi_signal'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Date} _date
 */
InlineResponse2009RsiData.prototype._date = undefined;

/**
 * @member {Number} rsi
 */
InlineResponse2009RsiData.prototype.rsi = undefined;

/**
 * One of \"oversold\", \"overbought\", \"neutral\"
 * @member {String} rsiSignal
 */
InlineResponse2009RsiData.prototype.rsiSignal = undefined;

