<?php
/**
 * CryptoCurrencyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Currencydatafeed.com API V2
 *
 * > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found.
 *
 * OpenAPI spec version: 2.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.68
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CryptoCurrencyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CryptoCurrencyApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCryptoExtendedHistory
     *
     * Get extended historical close prices for a specific crypto pair on an exchange.
     *
     */
    public function testGetCryptoExtendedHistory()
    {
    }

    /**
     * Test case for getCryptoExtendedMinuteHistory
     *
     * Get intraday (minute-level) price history for a specific crypto pair on an exchange.
     *
     */
    public function testGetCryptoExtendedMinuteHistory()
    {
    }

    /**
     * Test case for getCryptoHistory
     *
     * Get historical close prices for a cryptocurrency.
     *
     */
    public function testGetCryptoHistory()
    {
    }

    /**
     * Test case for getCryptoLive
     *
     * Get live data for one or more cryptocurrencies.
     *
     */
    public function testGetCryptoLive()
    {
    }

    /**
     * Test case for getCryptoLiveByExchange
     *
     * Get live crypto data for all pairs from a specific exchange.
     *
     */
    public function testGetCryptoLiveByExchange()
    {
    }

    /**
     * Test case for getCryptoLiveExtended
     *
     * Get extended live data for one or more crypto pairs from specific exchanges.
     *
     */
    public function testGetCryptoLiveExtended()
    {
    }

    /**
     * Test case for getCryptoMarketFearGreedIndex
     *
     * Get Crypto Market Fear & Greed Index.
     *
     */
    public function testGetCryptoMarketFearGreedIndex()
    {
    }

    /**
     * Test case for getCryptoMinuteHistory
     *
     * Get 1-minute historical close prices for a cryptocurrency (up to 48 hours).
     *
     */
    public function testGetCryptoMinuteHistory()
    {
    }

    /**
     * Test case for getCryptoOnchainMetrics
     *
     * Get on-chain metrics for Bitcoin and crypto markets.
     *
     */
    public function testGetCryptoOnchainMetrics()
    {
    }

    /**
     * Test case for getCryptoPerformance
     *
     * Get performance of a single cryptocurrency over various periods.
     *
     */
    public function testGetCryptoPerformance()
    {
    }
}
