/**
 * Currencydatafeed.com API V2
 * > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found. 
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param symbol Symbol queried
 * @param percentageChange1h Percentage change in the last 1 hour
 * @param percentageChange4h Percentage change in the last 4 hours
 * @param percentageChange1d Percentage change in the last 1 day
 * @param percentageChange7d Percentage change in the last 7 days
 * @param percentageChange30d Percentage change in the last 30 days
 * @param percentageChange90d Percentage change in the last 90 days
 * @param percentageChange180d Percentage change in the last 180 days
 * @param percentageChange270d Percentage change in the last 270 days
 * @param percentageChange365d Percentage change in the last 365 days
 * @param percentageChange720d Percentage change in the last 720 days
 */
data class InlineResponse2004Data (

    /* Symbol queried */
    val symbol: kotlin.String? = null,
    /* Percentage change in the last 1 hour */
    val percentageChange1h: java.math.BigDecimal? = null,
    /* Percentage change in the last 4 hours */
    val percentageChange4h: java.math.BigDecimal? = null,
    /* Percentage change in the last 1 day */
    val percentageChange1d: java.math.BigDecimal? = null,
    /* Percentage change in the last 7 days */
    val percentageChange7d: java.math.BigDecimal? = null,
    /* Percentage change in the last 30 days */
    val percentageChange30d: java.math.BigDecimal? = null,
    /* Percentage change in the last 90 days */
    val percentageChange90d: java.math.BigDecimal? = null,
    /* Percentage change in the last 180 days */
    val percentageChange180d: java.math.BigDecimal? = null,
    /* Percentage change in the last 270 days */
    val percentageChange270d: java.math.BigDecimal? = null,
    /* Percentage change in the last 365 days */
    val percentageChange365d: java.math.BigDecimal? = null,
    /* Percentage change in the last 720 days */
    val percentageChange720d: java.math.BigDecimal? = null
) {
}