<?php
/**
 * InlineResponse2001DataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Currencydatafeed.com API V2
 *
 * > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found.
 *
 * OpenAPI spec version: 2.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.68
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2001DataTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2001Data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2001DataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2001Data"
     */
    public function testInlineResponse2001Data()
    {
    }

    /**
     * Test attribute "symbol"
     */
    public function testPropertySymbol()
    {
    }

    /**
     * Test attribute "last"
     */
    public function testPropertyLast()
    {
    }

    /**
     * Test attribute "change"
     */
    public function testPropertyChange()
    {
    }

    /**
     * Test attribute "change_percent"
     */
    public function testPropertyChangePercent()
    {
    }

    /**
     * Test attribute "weekly_change"
     */
    public function testPropertyWeeklyChange()
    {
    }

    /**
     * Test attribute "weekly_change_percent"
     */
    public function testPropertyWeeklyChangePercent()
    {
    }

    /**
     * Test attribute "monthly_change"
     */
    public function testPropertyMonthlyChange()
    {
    }

    /**
     * Test attribute "monthly_change_percent"
     */
    public function testPropertyMonthlyChangePercent()
    {
    }

    /**
     * Test attribute "yearly_change"
     */
    public function testPropertyYearlyChange()
    {
    }

    /**
     * Test attribute "yearly_change_percent"
     */
    public function testPropertyYearlyChangePercent()
    {
    }

    /**
     * Test attribute "ask"
     */
    public function testPropertyAsk()
    {
    }

    /**
     * Test attribute "bid"
     */
    public function testPropertyBid()
    {
    }

    /**
     * Test attribute "daily_lowest"
     */
    public function testPropertyDailyLowest()
    {
    }

    /**
     * Test attribute "daily_highest"
     */
    public function testPropertyDailyHighest()
    {
    }

    /**
     * Test attribute "open_today"
     */
    public function testPropertyOpenToday()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }
}
