/*
 * Currencydatafeed.com API V2
 *
 * > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found. 
 *
 * API version: 2.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001Data struct {
	// Pair symbol (e.g. \"EURUSD\", \"BTCUSD\")
	Symbol string `json:"symbol,omitempty"`
	// Last trade price
	Last float64 `json:"last,omitempty"`
	// Absolute daily change
	Change float64 `json:"change,omitempty"`
	// Daily change as a percent
	ChangePercent float64 `json:"change_percent,omitempty"`
	// Absolute weekly change
	WeeklyChange float64 `json:"weekly_change,omitempty"`
	// Weekly change as a percent
	WeeklyChangePercent float64 `json:"weekly_change_percent,omitempty"`
	// Absolute monthly change
	MonthlyChange float64 `json:"monthly_change,omitempty"`
	// Monthly change as a percent
	MonthlyChangePercent float64 `json:"monthly_change_percent,omitempty"`
	// Absolute yearly change
	YearlyChange float64 `json:"yearly_change,omitempty"`
	// Yearly change as a percent
	YearlyChangePercent float64 `json:"yearly_change_percent,omitempty"`
	// Ask price
	Ask float64 `json:"ask,omitempty"`
	// Bid price
	Bid float64 `json:"bid,omitempty"`
	// Lowest price of the day
	DailyLowest float64 `json:"daily_lowest,omitempty"`
	// Highest price of the day
	DailyHighest float64 `json:"daily_highest,omitempty"`
	// Open price of the day
	OpenToday float64 `json:"open_today,omitempty"`
	// Time of the last update (\"YYYY-MM-DD HH:mm:ss\")
	Date string `json:"date,omitempty"`
}
