/*
 * Currencydatafeed.com API V2
 *
 * > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found. 
 *
 * API version: 2.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type InlineResponse20012Data struct {
	// Cryptocurrency pair (e.g. BTCUSDT)
	Symbol string `json:"symbol,omitempty"`
	// Last trade price
	Last float64 `json:"last,omitempty"`
	// 24h low price
	Low float64 `json:"low,omitempty"`
	// 24h high price
	High float64 `json:"high,omitempty"`
	// Previous day's closing price
	PreviousDay float64 `json:"previous_day,omitempty"`
	// 24h change percentage
	DailyChangePercentage float64 `json:"daily_change_percentage,omitempty"`
	// Exchange/market name (e.g. binance, bybit)
	Source string `json:"source,omitempty"`
	// Last update time
	Updated time.Time `json:"updated,omitempty"`
}
