/*
 * Currencydatafeed.com API V2
 *
 * > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found. 
 *
 * API version: 2.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2008Data struct {
	// The queried symbol
	Symbol string `json:"symbol,omitempty"`
	// Pivot point
	Pivot float64 `json:"pivot,omitempty"`
	// First resistance level
	Resistance1 float64 `json:"resistance1,omitempty"`
	// First support level
	Support1 float64 `json:"support1,omitempty"`
	// Second resistance level
	Resistance2 float64 `json:"resistance2,omitempty"`
	// Second support level
	Support2 float64 `json:"support2,omitempty"`
	// Third resistance level
	Resistance3 float64 `json:"resistance3,omitempty"`
	// Third support level
	Support3 float64 `json:"support3,omitempty"`
	// Bollinger Bands upper value (if enough data)
	BollingerUpper float64 `json:"bollinger_upper,omitempty"`
	// Bollinger Bands lower value (if enough data)
	BollingerLower float64 `json:"bollinger_lower,omitempty"`
}
