# coding: utf-8

"""
    Currencydatafeed.com API V2

    > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found.   # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Currencydatafeed.com API V2",
    author_email="",
    url="",
    keywords=["Swagger", "Currencydatafeed.com API V2"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    &gt; 📘 **Looking for V1 API documentation?**   &gt; Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP &#x60;Authorization&#x60; header:  &#x60;&#x60;&#x60; Authorization: Bearer YOUR_API_TOKEN &#x60;&#x60;&#x60;  **Example (cURL):** &#x60;&#x60;&#x60;shell curl -H \&quot;Authorization: Bearer YOUR_API_TOKEN\&quot; \\   \&quot;https://currencydatafeed.com/api/v2/live-rates\&quot; &#x60;&#x60;&#x60;  **Alternative:** You may also send the token as a &#x60;token&#x60; query parameter, but this is less secure and not recommended:  &#x60;&#x60;&#x60; https://currencydatafeed.com/api/v2/live-rates?token&#x3D;YOUR_API_TOKEN &#x60;&#x60;&#x60;  &gt; The API first checks the Authorization header, then the &#x60;token&#x60; parameter if no header is found.   # noqa: E501
    """
)
