/*
 * Currencydatafeed.com API V2
 * > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found. 
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;
/**
 * InlineResponse2005Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-06-16T10:33:10.614284809Z[GMT]")

public class InlineResponse2005Data {
  @SerializedName("currency")
  private String currency = null;

  @SerializedName("open")
  private BigDecimal open = null;

  @SerializedName("high")
  private BigDecimal high = null;

  @SerializedName("low")
  private BigDecimal low = null;

  @SerializedName("close")
  private BigDecimal close = null;

  @SerializedName("date")
  private OffsetDateTime date = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("error")
  private String error = null;

  public InlineResponse2005Data currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Queried or reversed pair symbol
   * @return currency
  **/
  @Schema(description = "Queried or reversed pair symbol")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public InlineResponse2005Data open(BigDecimal open) {
    this.open = open;
    return this;
  }

   /**
   * Open price (if available)
   * @return open
  **/
  @Schema(description = "Open price (if available)")
  public BigDecimal getOpen() {
    return open;
  }

  public void setOpen(BigDecimal open) {
    this.open = open;
  }

  public InlineResponse2005Data high(BigDecimal high) {
    this.high = high;
    return this;
  }

   /**
   * High price (if available)
   * @return high
  **/
  @Schema(description = "High price (if available)")
  public BigDecimal getHigh() {
    return high;
  }

  public void setHigh(BigDecimal high) {
    this.high = high;
  }

  public InlineResponse2005Data low(BigDecimal low) {
    this.low = low;
    return this;
  }

   /**
   * Low price (if available)
   * @return low
  **/
  @Schema(description = "Low price (if available)")
  public BigDecimal getLow() {
    return low;
  }

  public void setLow(BigDecimal low) {
    this.low = low;
  }

  public InlineResponse2005Data close(BigDecimal close) {
    this.close = close;
    return this;
  }

   /**
   * Close price (if available)
   * @return close
  **/
  @Schema(description = "Close price (if available)")
  public BigDecimal getClose() {
    return close;
  }

  public void setClose(BigDecimal close) {
    this.close = close;
  }

  public InlineResponse2005Data date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * Data timestamp
   * @return date
  **/
  @Schema(description = "Data timestamp")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public InlineResponse2005Data type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Data type (\&quot;original\&quot; or \&quot;reversed\&quot;)
   * @return type
  **/
  @Schema(description = "Data type (\"original\" or \"reversed\")")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public InlineResponse2005Data error(String error) {
    this.error = error;
    return this;
  }

   /**
   * Error message if no data is available
   * @return error
  **/
  @Schema(description = "Error message if no data is available")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2005Data inlineResponse2005Data = (InlineResponse2005Data) o;
    return Objects.equals(this.currency, inlineResponse2005Data.currency) &&
        Objects.equals(this.open, inlineResponse2005Data.open) &&
        Objects.equals(this.high, inlineResponse2005Data.high) &&
        Objects.equals(this.low, inlineResponse2005Data.low) &&
        Objects.equals(this.close, inlineResponse2005Data.close) &&
        Objects.equals(this.date, inlineResponse2005Data.date) &&
        Objects.equals(this.type, inlineResponse2005Data.type) &&
        Objects.equals(this.error, inlineResponse2005Data.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, open, high, low, close, date, type, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2005Data {\n");
    
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    open: ").append(toIndentedString(open)).append("\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    close: ").append(toIndentedString(close)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
