/*
 * Currencydatafeed.com API V2
 * > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found. 
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * InlineResponse2004Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-06-16T10:33:10.614284809Z[GMT]")

public class InlineResponse2004Data {
  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("PercentageChange_1h")
  private BigDecimal percentageChange1h = null;

  @SerializedName("PercentageChange_4h")
  private BigDecimal percentageChange4h = null;

  @SerializedName("PercentageChange_1d")
  private BigDecimal percentageChange1d = null;

  @SerializedName("PercentageChange_7d")
  private BigDecimal percentageChange7d = null;

  @SerializedName("PercentageChange_30d")
  private BigDecimal percentageChange30d = null;

  @SerializedName("PercentageChange_90d")
  private BigDecimal percentageChange90d = null;

  @SerializedName("PercentageChange_180d")
  private BigDecimal percentageChange180d = null;

  @SerializedName("PercentageChange_270d")
  private BigDecimal percentageChange270d = null;

  @SerializedName("PercentageChange_365d")
  private BigDecimal percentageChange365d = null;

  @SerializedName("PercentageChange_720d")
  private BigDecimal percentageChange720d = null;

  public InlineResponse2004Data symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Symbol queried
   * @return symbol
  **/
  @Schema(description = "Symbol queried")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public InlineResponse2004Data percentageChange1h(BigDecimal percentageChange1h) {
    this.percentageChange1h = percentageChange1h;
    return this;
  }

   /**
   * Percentage change in the last 1 hour
   * @return percentageChange1h
  **/
  @Schema(description = "Percentage change in the last 1 hour")
  public BigDecimal getPercentageChange1h() {
    return percentageChange1h;
  }

  public void setPercentageChange1h(BigDecimal percentageChange1h) {
    this.percentageChange1h = percentageChange1h;
  }

  public InlineResponse2004Data percentageChange4h(BigDecimal percentageChange4h) {
    this.percentageChange4h = percentageChange4h;
    return this;
  }

   /**
   * Percentage change in the last 4 hours
   * @return percentageChange4h
  **/
  @Schema(description = "Percentage change in the last 4 hours")
  public BigDecimal getPercentageChange4h() {
    return percentageChange4h;
  }

  public void setPercentageChange4h(BigDecimal percentageChange4h) {
    this.percentageChange4h = percentageChange4h;
  }

  public InlineResponse2004Data percentageChange1d(BigDecimal percentageChange1d) {
    this.percentageChange1d = percentageChange1d;
    return this;
  }

   /**
   * Percentage change in the last 1 day
   * @return percentageChange1d
  **/
  @Schema(description = "Percentage change in the last 1 day")
  public BigDecimal getPercentageChange1d() {
    return percentageChange1d;
  }

  public void setPercentageChange1d(BigDecimal percentageChange1d) {
    this.percentageChange1d = percentageChange1d;
  }

  public InlineResponse2004Data percentageChange7d(BigDecimal percentageChange7d) {
    this.percentageChange7d = percentageChange7d;
    return this;
  }

   /**
   * Percentage change in the last 7 days
   * @return percentageChange7d
  **/
  @Schema(description = "Percentage change in the last 7 days")
  public BigDecimal getPercentageChange7d() {
    return percentageChange7d;
  }

  public void setPercentageChange7d(BigDecimal percentageChange7d) {
    this.percentageChange7d = percentageChange7d;
  }

  public InlineResponse2004Data percentageChange30d(BigDecimal percentageChange30d) {
    this.percentageChange30d = percentageChange30d;
    return this;
  }

   /**
   * Percentage change in the last 30 days
   * @return percentageChange30d
  **/
  @Schema(description = "Percentage change in the last 30 days")
  public BigDecimal getPercentageChange30d() {
    return percentageChange30d;
  }

  public void setPercentageChange30d(BigDecimal percentageChange30d) {
    this.percentageChange30d = percentageChange30d;
  }

  public InlineResponse2004Data percentageChange90d(BigDecimal percentageChange90d) {
    this.percentageChange90d = percentageChange90d;
    return this;
  }

   /**
   * Percentage change in the last 90 days
   * @return percentageChange90d
  **/
  @Schema(description = "Percentage change in the last 90 days")
  public BigDecimal getPercentageChange90d() {
    return percentageChange90d;
  }

  public void setPercentageChange90d(BigDecimal percentageChange90d) {
    this.percentageChange90d = percentageChange90d;
  }

  public InlineResponse2004Data percentageChange180d(BigDecimal percentageChange180d) {
    this.percentageChange180d = percentageChange180d;
    return this;
  }

   /**
   * Percentage change in the last 180 days
   * @return percentageChange180d
  **/
  @Schema(description = "Percentage change in the last 180 days")
  public BigDecimal getPercentageChange180d() {
    return percentageChange180d;
  }

  public void setPercentageChange180d(BigDecimal percentageChange180d) {
    this.percentageChange180d = percentageChange180d;
  }

  public InlineResponse2004Data percentageChange270d(BigDecimal percentageChange270d) {
    this.percentageChange270d = percentageChange270d;
    return this;
  }

   /**
   * Percentage change in the last 270 days
   * @return percentageChange270d
  **/
  @Schema(description = "Percentage change in the last 270 days")
  public BigDecimal getPercentageChange270d() {
    return percentageChange270d;
  }

  public void setPercentageChange270d(BigDecimal percentageChange270d) {
    this.percentageChange270d = percentageChange270d;
  }

  public InlineResponse2004Data percentageChange365d(BigDecimal percentageChange365d) {
    this.percentageChange365d = percentageChange365d;
    return this;
  }

   /**
   * Percentage change in the last 365 days
   * @return percentageChange365d
  **/
  @Schema(description = "Percentage change in the last 365 days")
  public BigDecimal getPercentageChange365d() {
    return percentageChange365d;
  }

  public void setPercentageChange365d(BigDecimal percentageChange365d) {
    this.percentageChange365d = percentageChange365d;
  }

  public InlineResponse2004Data percentageChange720d(BigDecimal percentageChange720d) {
    this.percentageChange720d = percentageChange720d;
    return this;
  }

   /**
   * Percentage change in the last 720 days
   * @return percentageChange720d
  **/
  @Schema(description = "Percentage change in the last 720 days")
  public BigDecimal getPercentageChange720d() {
    return percentageChange720d;
  }

  public void setPercentageChange720d(BigDecimal percentageChange720d) {
    this.percentageChange720d = percentageChange720d;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2004Data inlineResponse2004Data = (InlineResponse2004Data) o;
    return Objects.equals(this.symbol, inlineResponse2004Data.symbol) &&
        Objects.equals(this.percentageChange1h, inlineResponse2004Data.percentageChange1h) &&
        Objects.equals(this.percentageChange4h, inlineResponse2004Data.percentageChange4h) &&
        Objects.equals(this.percentageChange1d, inlineResponse2004Data.percentageChange1d) &&
        Objects.equals(this.percentageChange7d, inlineResponse2004Data.percentageChange7d) &&
        Objects.equals(this.percentageChange30d, inlineResponse2004Data.percentageChange30d) &&
        Objects.equals(this.percentageChange90d, inlineResponse2004Data.percentageChange90d) &&
        Objects.equals(this.percentageChange180d, inlineResponse2004Data.percentageChange180d) &&
        Objects.equals(this.percentageChange270d, inlineResponse2004Data.percentageChange270d) &&
        Objects.equals(this.percentageChange365d, inlineResponse2004Data.percentageChange365d) &&
        Objects.equals(this.percentageChange720d, inlineResponse2004Data.percentageChange720d);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, percentageChange1h, percentageChange4h, percentageChange1d, percentageChange7d, percentageChange30d, percentageChange90d, percentageChange180d, percentageChange270d, percentageChange365d, percentageChange720d);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2004Data {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    percentageChange1h: ").append(toIndentedString(percentageChange1h)).append("\n");
    sb.append("    percentageChange4h: ").append(toIndentedString(percentageChange4h)).append("\n");
    sb.append("    percentageChange1d: ").append(toIndentedString(percentageChange1d)).append("\n");
    sb.append("    percentageChange7d: ").append(toIndentedString(percentageChange7d)).append("\n");
    sb.append("    percentageChange30d: ").append(toIndentedString(percentageChange30d)).append("\n");
    sb.append("    percentageChange90d: ").append(toIndentedString(percentageChange90d)).append("\n");
    sb.append("    percentageChange180d: ").append(toIndentedString(percentageChange180d)).append("\n");
    sb.append("    percentageChange270d: ").append(toIndentedString(percentageChange270d)).append("\n");
    sb.append("    percentageChange365d: ").append(toIndentedString(percentageChange365d)).append("\n");
    sb.append("    percentageChange720d: ").append(toIndentedString(percentageChange720d)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
