//
// InlineResponse20013Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse20013Data: Codable {

    /** Date (YYYY-MM-DD) */
    public var date: Date?
    /** Close price for the day */
    public var close: Decimal?

    public init(date: Date? = nil, close: Decimal? = nil) {
        self.date = date
        self.close = close
    }


}
