//
// InlineResponse2005.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2005: Codable {

    public var status: Bool?
    public var data: [InlineResponse2005Data]?

    public init(status: Bool? = nil, data: [InlineResponse2005Data]? = nil) {
        self.status = status
        self.data = data
    }


}
