//
// InlineResponse2004.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2004: Codable {

    public var success: Bool?
    public var data: InlineResponse2004Data?

    public init(success: Bool? = nil, data: InlineResponse2004Data? = nil) {
        self.success = success
        self.data = data
    }


}
