//
// InlineResponse2002.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2002: Codable {

    /** The target currency code (e.g., &#x60;USD&#x60;) */
    public var currency: String?
    /** The latest conversion rate as a string */
    public var last: String?
    /** The timestamp of the last rate update */
    public var date: Date?

    public init(currency: String? = nil, last: String? = nil, date: Date? = nil) {
        self.currency = currency
        self.last = last
        self.date = date
    }


}
