//
// InlineResponse2003Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2003Data: Codable {

    /** Source currency code */
    public var from: String?
    /** Target currency code */
    public var to: String?
    /** Amount to convert */
    public var amount: Decimal?
    /** Conversion rate applied */
    public var rate: Decimal?
    /** Result of the conversion (amount * rate) */
    public var conversionResult: Decimal?
    /** Rate date/time used for conversion */
    public var date: Date?
    /** Error message (present only if no data is available) */
    public var error: String?

    public init(from: String? = nil, to: String? = nil, amount: Decimal? = nil, rate: Decimal? = nil, conversionResult: Decimal? = nil, date: Date? = nil, error: String? = nil) {
        self.from = from
        self.to = to
        self.amount = amount
        self.rate = rate
        self.conversionResult = conversionResult
        self.date = date
        self.error = error
    }

    public enum CodingKeys: String, CodingKey { 
        case from
        case to
        case amount
        case rate
        case conversionResult = "conversion_result"
        case date
        case error
    }

}
