//
// InlineResponse20010Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse20010Data: Codable {

    /** Cryptocurrency symbol (e.g. BTC, ETH) */
    public var symbol: String?
    /** Last trade price in USD */
    public var last: Decimal?
    /** 24h change percentage */
    public var dailyChangePercentage: Decimal?
    /** Price in BTC, if available */
    public var lastBtc: Decimal?
    /** 24h low price */
    public var low: Decimal?
    /** 24h high price */
    public var high: Decimal?
    /** Time of the last update */
    public var updated: Date?
    /** Source table */
    public var source: String?

    public init(symbol: String? = nil, last: Decimal? = nil, dailyChangePercentage: Decimal? = nil, lastBtc: Decimal? = nil, low: Decimal? = nil, high: Decimal? = nil, updated: Date? = nil, source: String? = nil) {
        self.symbol = symbol
        self.last = last
        self.dailyChangePercentage = dailyChangePercentage
        self.lastBtc = lastBtc
        self.low = low
        self.high = high
        self.updated = updated
        self.source = source
    }

    public enum CodingKeys: String, CodingKey { 
        case symbol
        case last
        case dailyChangePercentage = "daily_change_percentage"
        case lastBtc = "last_btc"
        case low
        case high
        case updated
        case source
    }

}
