//
// InlineResponse2009RsiData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2009RsiData: Codable {

    public var date: Date?
    public var rsi: Decimal?
    /** One of \&quot;oversold\&quot;, \&quot;overbought\&quot;, \&quot;neutral\&quot; */
    public var rsiSignal: String?

    public init(date: Date? = nil, rsi: Decimal? = nil, rsiSignal: String? = nil) {
        self.date = date
        self.rsi = rsi
        self.rsiSignal = rsiSignal
    }

    public enum CodingKeys: String, CodingKey { 
        case date
        case rsi
        case rsiSignal = "rsi_signal"
    }

}
