//
// InlineResponse20016Data.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse20016Data: Codable {

    /** Timestamp (YYYY-MM-DD HH:MM:SS) */
    public var date: Date?
    /** Closing price at that minute */
    public var close: Decimal?

    public init(date: Date? = nil, close: Decimal? = nil) {
        self.date = date
        self.close = close
    }


}
