//
// InlineResponse2008.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2008: Codable {

    public var success: Bool?
    public var data: InlineResponse2008Data?
    /** Error message if calculation is not possible */
    public var error: String?

    public init(success: Bool? = nil, data: InlineResponse2008Data? = nil, error: String? = nil) {
        self.success = success
        self.data = data
        self.error = error
    }


}
