//
// InlineResponse2001.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2001: Codable {

    public var success: Bool?
    public var data: [InlineResponse2001Data]?

    public init(success: Bool? = nil, data: [InlineResponse2001Data]? = nil) {
        self.success = success
        self.data = data
    }


}
