# coding: utf-8

"""
    Currencydatafeed.com API V2

    > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found.   # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20019Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_1d': 'float',
        '_7d': 'float',
        '_15d': 'float',
        '_30d': 'float',
        '_90d': 'float',
        '_180d': 'float',
        '_270d': 'float',
        '_365d': 'float',
        '_720d': 'float'
    }

    attribute_map = {
        '_1d': '1d',
        '_7d': '7d',
        '_15d': '15d',
        '_30d': '30d',
        '_90d': '90d',
        '_180d': '180d',
        '_270d': '270d',
        '_365d': '365d',
        '_720d': '720d'
    }

    def __init__(self, _1d=None, _7d=None, _15d=None, _30d=None, _90d=None, _180d=None, _270d=None, _365d=None, _720d=None):  # noqa: E501
        """InlineResponse20019Data - a model defined in Swagger"""  # noqa: E501
        self.__1d = None
        self.__7d = None
        self.__15d = None
        self.__30d = None
        self.__90d = None
        self.__180d = None
        self.__270d = None
        self.__365d = None
        self.__720d = None
        self.discriminator = None
        if _1d is not None:
            self._1d = _1d
        if _7d is not None:
            self._7d = _7d
        if _15d is not None:
            self._15d = _15d
        if _30d is not None:
            self._30d = _30d
        if _90d is not None:
            self._90d = _90d
        if _180d is not None:
            self._180d = _180d
        if _270d is not None:
            self._270d = _270d
        if _365d is not None:
            self._365d = _365d
        if _720d is not None:
            self._720d = _720d

    @property
    def _1d(self):
        """Gets the _1d of this InlineResponse20019Data.  # noqa: E501

        Percent change over 1 day  # noqa: E501

        :return: The _1d of this InlineResponse20019Data.  # noqa: E501
        :rtype: float
        """
        return self.__1d

    @_1d.setter
    def _1d(self, _1d):
        """Sets the _1d of this InlineResponse20019Data.

        Percent change over 1 day  # noqa: E501

        :param _1d: The _1d of this InlineResponse20019Data.  # noqa: E501
        :type: float
        """

        self.__1d = _1d

    @property
    def _7d(self):
        """Gets the _7d of this InlineResponse20019Data.  # noqa: E501

        Percent change over 7 days  # noqa: E501

        :return: The _7d of this InlineResponse20019Data.  # noqa: E501
        :rtype: float
        """
        return self.__7d

    @_7d.setter
    def _7d(self, _7d):
        """Sets the _7d of this InlineResponse20019Data.

        Percent change over 7 days  # noqa: E501

        :param _7d: The _7d of this InlineResponse20019Data.  # noqa: E501
        :type: float
        """

        self.__7d = _7d

    @property
    def _15d(self):
        """Gets the _15d of this InlineResponse20019Data.  # noqa: E501

        Percent change over 15 days  # noqa: E501

        :return: The _15d of this InlineResponse20019Data.  # noqa: E501
        :rtype: float
        """
        return self.__15d

    @_15d.setter
    def _15d(self, _15d):
        """Sets the _15d of this InlineResponse20019Data.

        Percent change over 15 days  # noqa: E501

        :param _15d: The _15d of this InlineResponse20019Data.  # noqa: E501
        :type: float
        """

        self.__15d = _15d

    @property
    def _30d(self):
        """Gets the _30d of this InlineResponse20019Data.  # noqa: E501

        Percent change over 30 days  # noqa: E501

        :return: The _30d of this InlineResponse20019Data.  # noqa: E501
        :rtype: float
        """
        return self.__30d

    @_30d.setter
    def _30d(self, _30d):
        """Sets the _30d of this InlineResponse20019Data.

        Percent change over 30 days  # noqa: E501

        :param _30d: The _30d of this InlineResponse20019Data.  # noqa: E501
        :type: float
        """

        self.__30d = _30d

    @property
    def _90d(self):
        """Gets the _90d of this InlineResponse20019Data.  # noqa: E501

        Percent change over 90 days  # noqa: E501

        :return: The _90d of this InlineResponse20019Data.  # noqa: E501
        :rtype: float
        """
        return self.__90d

    @_90d.setter
    def _90d(self, _90d):
        """Sets the _90d of this InlineResponse20019Data.

        Percent change over 90 days  # noqa: E501

        :param _90d: The _90d of this InlineResponse20019Data.  # noqa: E501
        :type: float
        """

        self.__90d = _90d

    @property
    def _180d(self):
        """Gets the _180d of this InlineResponse20019Data.  # noqa: E501

        Percent change over 180 days  # noqa: E501

        :return: The _180d of this InlineResponse20019Data.  # noqa: E501
        :rtype: float
        """
        return self.__180d

    @_180d.setter
    def _180d(self, _180d):
        """Sets the _180d of this InlineResponse20019Data.

        Percent change over 180 days  # noqa: E501

        :param _180d: The _180d of this InlineResponse20019Data.  # noqa: E501
        :type: float
        """

        self.__180d = _180d

    @property
    def _270d(self):
        """Gets the _270d of this InlineResponse20019Data.  # noqa: E501

        Percent change over 270 days  # noqa: E501

        :return: The _270d of this InlineResponse20019Data.  # noqa: E501
        :rtype: float
        """
        return self.__270d

    @_270d.setter
    def _270d(self, _270d):
        """Sets the _270d of this InlineResponse20019Data.

        Percent change over 270 days  # noqa: E501

        :param _270d: The _270d of this InlineResponse20019Data.  # noqa: E501
        :type: float
        """

        self.__270d = _270d

    @property
    def _365d(self):
        """Gets the _365d of this InlineResponse20019Data.  # noqa: E501

        Percent change over 365 days  # noqa: E501

        :return: The _365d of this InlineResponse20019Data.  # noqa: E501
        :rtype: float
        """
        return self.__365d

    @_365d.setter
    def _365d(self, _365d):
        """Sets the _365d of this InlineResponse20019Data.

        Percent change over 365 days  # noqa: E501

        :param _365d: The _365d of this InlineResponse20019Data.  # noqa: E501
        :type: float
        """

        self.__365d = _365d

    @property
    def _720d(self):
        """Gets the _720d of this InlineResponse20019Data.  # noqa: E501

        Percent change over 720 days  # noqa: E501

        :return: The _720d of this InlineResponse20019Data.  # noqa: E501
        :rtype: float
        """
        return self.__720d

    @_720d.setter
    def _720d(self, _720d):
        """Sets the _720d of this InlineResponse20019Data.

        Percent change over 720 days  # noqa: E501

        :param _720d: The _720d of this InlineResponse20019Data.  # noqa: E501
        :type: float
        """

        self.__720d = _720d

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20019Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20019Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
