# coding: utf-8

"""
    Currencydatafeed.com API V2

    > 📘 **Looking for V1 API documentation?**   > Visit: [https://currencydatafeed.com/documentation.php](https://currencydatafeed.com/documentation.php)   A comprehensive data API to retrieve live and historical prices for currency pairs and cryptocurrencies, including technical analysis endpoints and on-chain metrics.  ## Authentication  All endpoints require an API token.  **Recommended:** Send your API token as a Bearer token in the HTTP `Authorization` header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  **Example (cURL):** ```shell curl -H \"Authorization: Bearer YOUR_API_TOKEN\" \\   \"https://currencydatafeed.com/api/v2/live-rates\" ```  **Alternative:** You may also send the token as a `token` query parameter, but this is less secure and not recommended:  ``` https://currencydatafeed.com/api/v2/live-rates?token=YOUR_API_TOKEN ```  > The API first checks the Authorization header, then the `token` parameter if no header is found.   # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2006(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'bool',
        'currency': 'str',
        '_from': 'date',
        'to': 'date',
        'data': 'list[InlineResponse2006Data]'
    }

    attribute_map = {
        'status': 'status',
        'currency': 'currency',
        '_from': 'from',
        'to': 'to',
        'data': 'data'
    }

    def __init__(self, status=None, currency=None, _from=None, to=None, data=None):  # noqa: E501
        """InlineResponse2006 - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._currency = None
        self.__from = None
        self._to = None
        self._data = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if currency is not None:
            self.currency = currency
        if _from is not None:
            self._from = _from
        if to is not None:
            self.to = to
        if data is not None:
            self.data = data

    @property
    def status(self):
        """Gets the status of this InlineResponse2006.  # noqa: E501


        :return: The status of this InlineResponse2006.  # noqa: E501
        :rtype: bool
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse2006.


        :param status: The status of this InlineResponse2006.  # noqa: E501
        :type: bool
        """

        self._status = status

    @property
    def currency(self):
        """Gets the currency of this InlineResponse2006.  # noqa: E501

        The queried currency pair  # noqa: E501

        :return: The currency of this InlineResponse2006.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this InlineResponse2006.

        The queried currency pair  # noqa: E501

        :param currency: The currency of this InlineResponse2006.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def _from(self):
        """Gets the _from of this InlineResponse2006.  # noqa: E501

        Start date of the query  # noqa: E501

        :return: The _from of this InlineResponse2006.  # noqa: E501
        :rtype: date
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this InlineResponse2006.

        Start date of the query  # noqa: E501

        :param _from: The _from of this InlineResponse2006.  # noqa: E501
        :type: date
        """

        self.__from = _from

    @property
    def to(self):
        """Gets the to of this InlineResponse2006.  # noqa: E501

        End date of the query  # noqa: E501

        :return: The to of this InlineResponse2006.  # noqa: E501
        :rtype: date
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this InlineResponse2006.

        End date of the query  # noqa: E501

        :param to: The to of this InlineResponse2006.  # noqa: E501
        :type: date
        """

        self._to = to

    @property
    def data(self):
        """Gets the data of this InlineResponse2006.  # noqa: E501


        :return: The data of this InlineResponse2006.  # noqa: E501
        :rtype: list[InlineResponse2006Data]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this InlineResponse2006.


        :param data: The data of this InlineResponse2006.  # noqa: E501
        :type: list[InlineResponse2006Data]
        """

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2006, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2006):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
